# The module's main settings.
security_review.settings:
  type: config_object
  mapping:
    policy_constraints:
      type: sequence
      label: 'Checks'
      sequence:
        type: security_review.check.[id]
        label: 'Check'

# Defines a security check's skip informations and settings.
security_review.check:
  type: mapping
  mapping:
    id:
      type: string
      label: 'Check ID'
    enabled:
      type: boolean
      label: 'Enabled'